AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Repair Work Order System - Ultimate Auto-Deploy Template

Globals:
  Function:
    Runtime: python3.9
    Timeout: 30
    MemorySize: 256
    Environment:
      Variables:
        TABLE_NAME: !Ref TicketTable
        SQS_QUEUE_URL: !Ref TicketQueue
        S3_BUCKET_NAME: !Ref RepairImageBucket
        SNS_TOPIC_ARN: !Ref TicketNotificationTopic

Resources:
  # --- 1. Cognito 認證系統 ---
  RepairUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: "User pool - vhimgh"
      AutoVerifiedAttributes: [email]
      Schema:
        - Name: email
          AttributeType: String
          Required: true

  AdminGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: "Admin"
      Description: "Administrators"
      UserPoolId: !Ref RepairUserPool

  RepairUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: "WebClient"
      UserPoolId: !Ref RepairUserPool

  # --- 2. 儲存與資料庫 ---
  TicketTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: TicketTable
      PrimaryKey: { Name: ticket_id, Type: String }

  RepairImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "repair-system-images-${AWS::AccountId}"

  # --- 3. 前端網頁儲存桶 (Static Website) ---
  FrontendWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "repair-system-web-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendWebsiteBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${FrontendWebsiteBucket}/*"

  # --- 4. 非同步處理 (SQS & SNS) ---
  TicketQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "TicketQueue"

  TicketNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "TicketNotificationTopic"

  MyEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: "11211109@gm.nttu.edu.tw" 
      Protocol: email
      TopicArn: !Ref TicketNotificationTopic

  # --- 5. API Gateway ---
  RepairApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors: "'*'"

  # --- 6. Lambda Functions ---
  TicketAPIHandler:
    Type: AWS::Serverless::Function
    Properties:
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      CodeUri: api/
      Handler: TicketAPIHandler.lambda_handler
      Events:
        ApiEvent:
          Type: Api
          Properties: { Path: /tickets, Method: ANY, RestApiId: !Ref RepairApi }

  TicketNotificationWorker:
    Type: AWS::Serverless::Function
    Properties:
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      CodeUri: api/
      Handler: TicketNotificationWorker.lambda_handler
      Events:
        SQSTrigger:
          Type: SQS
          Properties: { Queue: !GetAtt TicketQueue.Arn, BatchSize: 10 }

Outputs:
  ApiEndpoint:
    Value: !Sub "https://${RepairApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  UserPoolId:
    Value: !Ref RepairUserPool
  UserPoolClientId:
    Value: !Ref RepairUserPoolClient
  WebsiteURL:
    Value: !GetAtt FrontendWebsiteBucket.WebsiteURL